project:
  type: website
  output-dir: docs
  preview: 
    browser: true
    port: 5555
    watch-inputs: true
    navigate: true
  render:
    - "*-hi.qmd"

website:
  title: "BIZKIT"
  description: "Bite sized, easy to digest stories from the world of business, economy, and finance."
  site-url: "https://bizkit.co.in"
  repo-url: "https://github.com/satvikraman/bizkit"
  search: true

  twitter-card:
    image: "/files/profiles/twitter_card.png"
    card-style: summary_large_image
    creator: "@satvikraman"
    site: "@satvikraman"
  
  open-graph: 
    image: "/files/profiles/twitter_card.png"
    locale: en_US  

  page-footer:
    left: |
      <div class="faux-block">{{< fa brands creative-commons >}} {{< var years >}} Satvik Raman</div>
      <div class="faux-block">All content licensed under<br>[{{< fa brands creative-commons >}} {{< fa brands creative-commons-by >}} Creative Commons CC BY 4.0](https://creativecommons.org/licenses/by/4.0/)</div>
    right: |
      <div class="faux-block">Made with {{< fa brands python >}} and [Quarto](https://quarto.org/)</div>
      <div class="faux-block">[View the source at {{< fa brands github >}} GitHub]({{< var github-url >}})</div>

  navbar:
    pinned: false
    left:
      - text: "परिचय"
        href: index-hi.html
      - text: "ब्लॉग"
        file: blog/index-hi.html

    right:
      - text: 🌐
        aria-label: Languages
        menu:
          - text: English
            href: ../index-en.html
          - text: हिन्दी
            href: ../index-hi.html
          - text: ಕನ್ನಡ
            href: ../index-kn.html
          - text: தமிழ்
            href: ../index-ta.html
          - text: తెలుగు
            href: ../index-te.html
          - text: Deutsch
            href: ../index-de.html

format:
  html:
    theme: journal
    css: 
      - /assets/styles.css
      - /assets/fonts-hi.css

lang: en-US
language:
  ui: en  # Default UI language